apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: platform
  namespace: fleet-local
spec:
  branch: main
  insecureSkipTLSVerify: false
  paths:
    - /cd
  repo: https://github.com/dbones/demo-workers.git
  targets:
    - clusterSelector:
        matchExpressions:
          - key: provider.cattle.io
            operator: NotIn
            values:
              - harvester
